---
# tasks file for roles.d/demo

- name: Inclusion de t창ches
  include_tasks:
    file: task_one.yml
  when: option|d(1) == 1

- name: Inclusion de t창ches
  include_tasks:
    file: task_two.yml
  when: option|d(1) == 2

- name: Inclusion de t창ches
  import_tasks:
    file: task_one.yml
  tags: t1

- name: Inclusion de t창ches
  include_tasks:
    file: task_two.yml
  tags: t2
