---
- name: Micro-TP-1
  hosts: srv
  become: true
  gather_facts: false

  tasks:
    - name: Création, si besoin, du groupe info
      ansible.builtin.group:
        name: info
        state: present

    - name: Création/Affectation de l'utilisateur curt au groupe info
      ansible.builtin.user:
        name: curt
        append: true
        groups: info
        state: present
