---
- name: Gestion du template index.html.j2
  hosts: www
  become: true

  tasks:
    - name: Traitement et transfert du template index.html.j2
      template:
        src: index.html.j2
        dest: "{{ document_root }}/index.html"
