---
- name: Copie du fichier index.html sur les serveurs www
  hosts: www
  become: true
  gather_facts: false

  tasks:
    - name: Copie
      copy:
        content: |-
          ligne 1
          ligne 2
          ligne 3
        dest: /tmp/data.txt
