---
- name: Modification du port d'écoute d'Apache
  hosts: www
  become: true
  gather_facts: false

  tasks:
    - name: Modif. du port d'écoute
      lineinfile:
        dest: /etc/apache2/ports.conf
        regex: ^Listen
        line: Listen 81

    - name: Redémarrage d'Apache
      systemd:
        name: apache2
        state: restarted
