---
- name: Inclusion de variables
  hosts: debiancli
  gather_facts: false

  tasks:
    - name: Inclusion du fichier de variables stage.yml
      include_vars:
        file: stage.yml

    - name: Affichage de la variable stage
      debug:
        msg: "La variable stage vaut: {{ stage }}"
