---
- name: Inclusion de variables (alternative avec vars_files)
  hosts: debiancli
  gather_facts: false

  vars_files:
    - vars/stage.yml

  tasks:
    - name: Affichage de la variable stage
      debug:
        msg: "La variable stage vaut: {{ stage }}"

    - name: Filtre length
      debug:
        msg: "Nombre de stagiaires: {{ stagiaires|length }}"
